const LIST_EQUIPO_START = 'LIST_EQUIPO_START';
const LIST_EQUIPO_SUCCESS = 'LIST_EQUIPO_SUCCESS';
const LIST_EQUIPO_FAIL = 'LIST_EQUIPO_FAIL';
const LIST_EQUIPO_FINALLY = 'LIST_EQUIPO_FINALLY';

const ADD_EQUIPO_START = 'ADD_EQUIPO_START';
const ADD_EQUIPO_SUCCESS = 'ADD_EQUIPO_SUCCESS';
const ADD_EQUIPO_FAIL = 'ADD_EQUIPO_FAIL';
const ADD_EQUIPO_FINALLY = 'ADD_EQUIPO_FINALLY';

export {
    LIST_EQUIPO_START,
    LIST_EQUIPO_SUCCESS,
    LIST_EQUIPO_FAIL,
    LIST_EQUIPO_FINALLY,
    ADD_EQUIPO_START,
    ADD_EQUIPO_SUCCESS,
    ADD_EQUIPO_FAIL,
    ADD_EQUIPO_FINALLY
}