const LIST_ESTADO_START = 'LIST_ESTADO_START';
const LIST_ESTADO_SUCCESS = 'LIST_ESTADO_SUCCESS';
const LIST_ESTADO_FAIL = 'LIST_ESTADO_FAIL';
const LIST_ESTADO_FINALLY = 'LIST_ESTADO_FINALLY';

const ADD_ESTADO_START = 'ADD_ESTADO_START';
const ADD_ESTADO_SUCCESS = 'ADD_ESTADO_SUCCESS';
const ADD_ESTADO_FAIL = 'ADD_ESTADO_FAIL';
const ADD_ESTADO_FINALLY = 'ADD_ESTADO_FINALLY';

export {
    LIST_ESTADO_START,
    LIST_ESTADO_SUCCESS,
    LIST_ESTADO_FAIL,
    LIST_ESTADO_FINALLY,
    ADD_ESTADO_START,
    ADD_ESTADO_SUCCESS,
    ADD_ESTADO_FAIL,
    ADD_ESTADO_FINALLY
}