const LIST_NIVEL_START = 'LIST_NIVEL_START';
const LIST_NIVEL_SUCCESS = 'LIST_NIVEL_SUCCESS';
const LIST_NIVEL_FAIL = 'LIST_NIVEL_FAIL';
const LIST_NIVEL_FINALLY = 'LIST_NIVEL_FINALLY';

const ADD_NIVEL_START = 'ADD_NIVEL_START';
const ADD_NIVEL_SUCCESS = 'ADD_NIVEL_SUCCESS';
const ADD_NIVEL_FAIL = 'ADD_NIVEL_FAIL';
const ADD_NIVEL_FINALLY = 'ADD_NIVEL_FINALLY';

export {
    LIST_NIVEL_START,
    LIST_NIVEL_SUCCESS,
    LIST_NIVEL_FAIL,
    LIST_NIVEL_FINALLY,
    ADD_NIVEL_START,
    ADD_NIVEL_SUCCESS,
    ADD_NIVEL_FAIL,
    ADD_NIVEL_FINALLY
}