const LIST_SEDE_START = 'LIST_SEDE_START';
const LIST_SEDE_SUCCESS = 'LIST_SEDE_SUCCESS';
const LIST_SEDE_FAIL = 'LIST_SEDE_FAIL';
const LIST_SEDE_FINALLY = 'LIST_SEDE_FINALLY';

const ADD_SEDE_START = 'ADD_SEDE_START';
const ADD_SEDE_SUCCESS = 'ADD_SEDE_SUCCESS';
const ADD_SEDE_FAIL = 'ADD_SEDE_FAIL';
const ADD_SEDE_FINALLY = 'ADD_SEDE_FINALLY';

export {
    LIST_SEDE_START,
    LIST_SEDE_SUCCESS,
    LIST_SEDE_FAIL,
    LIST_SEDE_FINALLY,
    ADD_SEDE_START,
    ADD_SEDE_SUCCESS,
    ADD_SEDE_FAIL,
    ADD_SEDE_FINALLY
}