const LIST_SEDE_START = 'LIST_SEDE_START';
const LIST_SEDE_SUCCESS = 'LIST_SEDE_SUCCESS';
const LIST_SEDE_FAIL = 'LIST_SEDE_FAIL';
const LIST_SEDE_FINALLY = 'LIST_SEDE_FINALLY';

export {
    LIST_SEDE_START,
    LIST_SEDE_SUCCESS,
    LIST_SEDE_FAIL,
    LIST_SEDE_FINALLY
}