const LIST_SOPORTE_START = 'LIST_SOPORTE_START';
const LIST_SOPORTE_SUCCESS = 'LIST_SOPORTE_SUCCESS';
const LIST_SOPORTE_FAIL = 'LIST_SOPORTE_FAIL';
const LIST_SOPORTE_FINALLY = 'LIST_SOPORTE_FINALLY';

const ADD_SOPORTE_START = 'ADD_SOPORTE_START';
const ADD_SOPORTE_SUCCESS = 'ADD_SOPORTE_SUCCESS';
const ADD_SOPORTE_FAIL = 'ADD_SOPORTE_FAIL';
const ADD_SOPORTE_FINALLY = 'ADD_SOPORTE_FINALLY';

export {
    LIST_SOPORTE_START,
    LIST_SOPORTE_SUCCESS,
    LIST_SOPORTE_FAIL,
    LIST_SOPORTE_FINALLY,
    ADD_SOPORTE_START,
    ADD_SOPORTE_SUCCESS,
    ADD_SOPORTE_FAIL,
    ADD_SOPORTE_FINALLY
}