const LIST_TICKET_START = 'LIST_TICKET_START';
const LIST_TICKET_SUCCESS = 'LIST_TICKET_SUCCESS';
const LIST_TICKET_FAIL = 'LIST_TICKET_FAIL';
const LIST_TICKET_FINALLY = 'LIST_TICKET_FINALLY';

const ADD_TICKET_START = 'ADD_TICKET_START';
const ADD_TICKET_SUCCESS = 'ADD_TICKET_SUCCESS';
const ADD_TICKET_FAIL = 'ADD_TICKET_FAIL';
const ADD_TICKET_FINALLY = 'ADD_TICKET_FINALLY';

export {
    LIST_TICKET_START,
    LIST_TICKET_SUCCESS,
    LIST_TICKET_FAIL,
    LIST_TICKET_FINALLY,
    ADD_TICKET_START,
    ADD_TICKET_SUCCESS,
    ADD_TICKET_FAIL,
    ADD_TICKET_FINALLY
}