const DO_LOGIN_START = 'DO_LOGIN_START';
const DO_LOGIN_SUCCESS = 'DO_LOGIN_SUCCESS';
const DO_LOGIN_FAIL = 'DO_LOGIN_FAIL';
const DO_LOGIN_FINALLY = 'DO_LOGIN_FINALLY';

const ADD_USUARIO_START = 'ADD_USUARIO_START';
const ADD_USUARIO_SUCCESS = 'ADD_USUARIO_SUCCESS';
const ADD_USUARIO_FAIL = 'ADD_USUARIO_FAIL';
const ADD_USUARIO_FINALLY = 'ADD_USUARIO_FINALLY';



export {
    DO_LOGIN_START,
    DO_LOGIN_SUCCESS,
    DO_LOGIN_FAIL,
    DO_LOGIN_FINALLY,
    ADD_USUARIO_START,
    ADD_USUARIO_SUCCESS,
    ADD_USUARIO_FAIL,
    ADD_USUARIO_FINALLY
}